services:
  - type: web
    name: gerenciador-territorios-api
    runtime: node
    plan: free
    buildpacks:
      - url: https://github.com/jontewks/puppeteer-heroku-buildpack
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true